POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "devjam",
    "password": "Devjam@gohard123",
    "email": "hdthien21@clc.fitus.edu.vn",
    "phonenumber": "0774689403",
    "gender": "non-binary",
    "role": "user"
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "tinongdan",
    "password": "Devjam@gohard123",
    "email": "nmdat21@clc.fitus.edu.vn",
    "phonenumber": "0374043354",
    "gender": "non-binary",
    "role": "user"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "hdthien21@clc.fitus.edu.vn",
    "password": "Devjam@gohard123"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "nmdat21@clc.fitus.edu.vn",
    "password": "Devjam@gohard123"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "hdthien21@clc.fitus.edu.vn",
    "password": "aaasd"
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "hwangdeokthien",
    "password": "Ducthien@123",
    "email": "huynhducthien41906@gmail.com",
    "phonenumber": "0912345678",
    "gender": "non-binary",
    "role": "user"
}

###

GET http://localhost:8080/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNlN2YwOWEwNjRjODk5NjhmYTQ5MjUiLCJpYXQiOjE2OTEzMzY1OTcsImV4cCI6MTY5MTk0MTM5N30.j3LwT8gsRsQqQ635rjemTlKjIeZcinmSRlWBI5_YAjk

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNlN2YwOWEwNjRjODk5NjhmYTQ5MjUiLCJpYXQiOjE2OTEzMzY1OTcsImV4cCI6MTY5MTk0MTM5N30.j3LwT8gsRsQqQ635rjemTlKjIeZcinmSRlWBI5_YAjk

{
    "type": "Donating",
    "title": "Donate Book",
    "body": "There are 10 literature books for children",
    "author": "",
    "item": [{
        "name": "Literature Books",
        "quantity": 10,
        "category": "Book"
    }],
    "status": "Verified",
    "location": "Tp HCM",
    "match": ["64d3c88aebfb9e7c0e62675c"]
}

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmY2Y5MzgwNDBmY2ZlZGFkODJkM2EiLCJpYXQiOjE2OTEzNDA3MDIsImV4cCI6MTY5MTk0NTUwMn0.LXM-Ui67NuAYM4z5novjrHz0TyS4ajH_cmkUfzk7N_k

{
    "type": "Receiving",
    "title": "Receive Socks",
    "body": "We are in need of 8 pairs of socks for children",
    "author": "",
    "item": [{
        "name": "Socks",
        "quantity": 8,
        "category": "Clothing"
    }],
    "location": "Tp HCM"
}

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmY2Y5MzgwNDBmY2ZlZGFkODJkM2EiLCJpYXQiOjE2OTEzNDA3MDIsImV4cCI6MTY5MTk0NTUwMn0.LXM-Ui67NuAYM4z5novjrHz0TyS4ajH_cmkUfzk7N_k

{
    "type": "Receiving",
    "title": "Receive Bikes",
    "body": "We are in need of 15 bikes and 15 helmets for children",
    "author": "",
    "item": [{
        "name": "Bike",
        "quantity": 15,
        "category": "Vehicle"
    }, {
        "name": "Helmet",
        "quantity": 15,
        "category": "Clothing"
    }],
    "location": "Tp HCM"
}

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmY2Y5MzgwNDBmY2ZlZGFkODJkM2EiLCJpYXQiOjE2OTEzNDA3MDIsImV4cCI6MTY5MTk0NTUwMn0.LXM-Ui67NuAYM4z5novjrHz0TyS4ajH_cmkUfzk7N_k

{
    "type": "Receiving",
    "title": "Receive Bikes",
    "body": "We are in need of 15 bikes for children",
    "author": "",
    "item": [{
        "name": "Bike",
        "quantity": 15,
        "category": "Vehicle"
    }],
    "status": "Published",
    "location": "Tp HCM",
    "match": []
}

###

GET http://localhost:8080/api/post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmY2Y5MzgwNDBmY2ZlZGFkODJkM2EiLCJpYXQiOjE2OTEzNDA3MDIsImV4cCI6MTY5MTk0NTUwMn0.LXM-Ui67NuAYM4z5novjrHz0TyS4ajH_cmkUfzk7N_k

###

GET http://localhost:8080/api/post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNlN2YwOWEwNjRjODk5NjhmYTQ5MjUiLCJpYXQiOjE2OTE1OTc4ODgsImV4cCI6MTY5MjIwMjY4OH0._lmRWeTvOFcvi_nISf8-99YdGVxaL82vPPdUlzF14hU

###

PUT http://localhost:8080/api/post/64d3c88aebfb9e7c0e62675c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmY2Y5MzgwNDBmY2ZlZGFkODJkM2EiLCJpYXQiOjE2OTEzNDA3MDIsImV4cCI6MTY5MTk0NTUwMn0.LXM-Ui67NuAYM4z5novjrHz0TyS4ajH_cmkUfzk7N_k

{
    "title": "Receive Books",
    "body": "We are in need of 10 literature books for high school students",
    "item": [{
        "name": "Literature books",
        "quantity": 10,
        "category": "Book"
    }]
}
