POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "devjam",
    "password": "Devjam@gohard123",
    "email": "hdthien21@clc.fitus.edu.vn",
    "fullName": "Dev Thi Jam",
    "dateOfBirth": "2023-06-09",
    "location": "Ho Chi Minh city",
    "phonenumber": "0774689403",
    "gender": "non-binary",
    "role": "user"
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "tinongdan",
    "password": "Devjam@gohard123",
    "email": "nmdat21@clc.fitus.edu.vn",
    "phonenumber": "0374043354",
    "gender": "non-binary",
    "role": "user"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "hdthien21@clc.fitus.edu.vn",
    "password": "Devjam@gohard123"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "nmdat21@clc.fitus.edu.vn",
    "password": "Devjam@gohard123"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "hdthien21@clc.fitus.edu.vn",
    "password": "aaasd"
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "hwangdeokthien",
    "password": "Ducthien@123",
    "email": "huynhducthien41906@gmail.com",
    "fullName": "Thien Huynh Duc",
    "dateOfBirth": "2003-08-16",
    "location": "Da Nang city",
    "phonenumber": "0912345678",
    "gender": "non-binary",
    "role": "user"
}

###

GET http://localhost:8080/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNlN2YwOWEwNjRjODk5NjhmYTQ5MjUiLCJpYXQiOjE2OTEzMzY1OTcsImV4cCI6MTY5MTk0MTM5N30.j3LwT8gsRsQqQ635rjemTlKjIeZcinmSRlWBI5_YAjk

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNlN2YwOWEwNjRjODk5NjhmYTQ5MjUiLCJpYXQiOjE2OTEzMzY1OTcsImV4cCI6MTY5MTk0MTM5N30.j3LwT8gsRsQqQ635rjemTlKjIeZcinmSRlWBI5_YAjk

{
    "type": "Donating",
    "title": "Donate Book",
    "body": "There are 10 literature books for children",
    "author": "",
    "item": [{
        "name": "Literature Books",
        "quantity": 10
    }],
    "status": "Verified",
    "location": "Tp HCM",
    "match": []
}

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0ZTEwNTk2ZGU0NjA3MTdhZTdmMmIiLCJpYXQiOjE2OTE2NzI4NDIsImV4cCI6MTY5MjI3NzY0Mn0.mSkf7qDNJyEohijuO-_ODPJ2oEqMjene3Galfcqb3ds

{
    "type": "Receiving",
    "title": "Receive Socks",
    "body": "We are in need of 8 pairs of socks for children",
    "author": "",
    "item": [{
        "name": "Socks",
        "quantity": 8,
        "category": "Clothing"
    }],
    "location": "Tp HCM"
}

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0ZTEwNTk2ZGU0NjA3MTdhZTdmMmIiLCJpYXQiOjE2OTE2NzI4NDIsImV4cCI6MTY5MjI3NzY0Mn0.mSkf7qDNJyEohijuO-_ODPJ2oEqMjene3Galfcqb3ds

{
    "type": "Receiving",
    "title": "Receive Bikes",
    "body": "We are in need of 15 bikes and 15 helmets for children",
    "author": "",
    "item": [{
        "name": "Bike",
        "quantity": 15,
        "category": "Vehicle"
    }, {
        "name": "Helmet",
        "quantity": 15,
        "category": "Clothing"
    }],
    "location": "Tp HCM",
    "isArchived": true
}

###

POST http://localhost:8080/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0ZTEwNTk2ZGU0NjA3MTdhZTdmMmIiLCJpYXQiOjE2OTE2NzI4NDIsImV4cCI6MTY5MjI3NzY0Mn0.mSkf7qDNJyEohijuO-_ODPJ2oEqMjene3Galfcqb3ds

{
    "type": "Receiving",
    "title": "Receive Bikes",
    "body": "We are in need of 15 bikes for children",
    "author": "",
    "item": [{
        "name": "Bike",
        "quantity": 15
    }],
    "status": "Waiting",
    "location": "Tp HCM",
    "match": [],
    "isArchived": false
}

###

GET http://localhost:8080/api/post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmY2Y5MzgwNDBmY2ZlZGFkODJkM2EiLCJpYXQiOjE2OTEzNDA3MDIsImV4cCI6MTY5MTk0NTUwMn0.LXM-Ui67NuAYM4z5novjrHz0TyS4ajH_cmkUfzk7N_k

###

GET http://localhost:8080/api/post/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0ZTEwNTk2ZGU0NjA3MTdhZTdmMmIiLCJpYXQiOjE2OTE2NzI4NDIsImV4cCI6MTY5MjI3NzY0Mn0.mSkf7qDNJyEohijuO-_ODPJ2oEqMjene3Galfcqb3ds

###

PUT http://localhost:8080/api/post/64d4eede22b2766afa9e1003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0ZTEwNTk2ZGU0NjA3MTdhZTdmMmIiLCJpYXQiOjE2OTE2NzI4NDIsImV4cCI6MTY5MjI3NzY0Mn0.mSkf7qDNJyEohijuO-_ODPJ2oEqMjene3Galfcqb3ds

{
    "title": "Receive Bikes and Helmets"
}

###

DELETE http://localhost:8080/api/post/64d4eede22b2766afa9e1003
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0ZTEwNTk2ZGU0NjA3MTdhZTdmMmIiLCJpYXQiOjE2OTE2NzI4NDIsImV4cCI6MTY5MjI3NzY0Mn0.mSkf7qDNJyEohijuO-_ODPJ2oEqMjene3Galfcqb3ds
